name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: amazonlinux
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo yum install -y python3 pip
          pip3 install -r requirements.txt
      - name: Run tests
        run: |
          python3 -m unittest discover -s tests

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name YourLambdaFunction --zip-file fileb://function.zip
      - name: Sync to S3
        run: |
          aws s3 sync . s3://your-s3-bucket/path

permissions:
  actions: read
  contents: read
  id-token: write
  lambda: write
  s3: write